### ISSUE TITLE
Other Proposal Docs

### ISSUE THREAD

**Issue by gmyenni** [weecology/portal-ltreb#7]
- [x] UFIRST checklist

- [x] References Cited

- [x] Budget

- [x] Budget Justification

- [x] Facilities, Equipment and Other Resources

- [x] Data Management Plan - 2 pages

**Comment by gmyenni** [comment]
@skmorgane just need you to confirm the following:

- [x] Biosketch

- [x] Current and Pending

- [x] Facilities

- [x] Collaborators and Other Affiliations (COA)

**Comment by skmorgane** [comment]
My current and pending still needs a title for LTREB, but is otherwise updated.

**Comment by gmyenni** [comment]
We also need to check that all 'Resulting pubs' from prior support are in the references. @ethanwhite I copied yours from the other proposal. @skmorgane I probably haven't gotten all of yours.

**Comment by skmorgane** [comment]
Ok, I have gone through the resulting pubs and they are all integrated into the references.
